create table if not exists provider_documents (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references providers(id) on delete cascade,
  original_name text not null,
  file_name text not null,
  mime_type text,
  file_size bigint,
  document_type text not null default 'Other',
  notes text,
  file_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_documents_document_type_check
    check (document_type in ('CV', 'Certificate', 'Company Profile', 'Contract', 'Portfolio', 'Reference', 'Other'))
);

create index if not exists provider_documents_provider_id_idx
  on provider_documents(provider_id, created_at desc);
