create table if not exists provider_documents (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references providers(id) on delete cascade,
  file_name text not null,
  original_name text,
  file_path text,
  file_url text,
  mime_type text,
  file_size bigint,
  document_type text not null default 'Other',
  notes text,
  uploaded_at timestamptz not null default now(),
  uploaded_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists provider_documents
  add column if not exists file_name text;
alter table if exists provider_documents
  add column if not exists original_name text;
alter table if exists provider_documents
  add column if not exists file_path text;
alter table if exists provider_documents
  add column if not exists file_url text;
alter table if exists provider_documents
  add column if not exists mime_type text;
alter table if exists provider_documents
  add column if not exists file_size bigint;
alter table if exists provider_documents
  add column if not exists document_type text;
alter table if exists provider_documents
  add column if not exists notes text;
alter table if exists provider_documents
  add column if not exists uploaded_at timestamptz;
alter table if exists provider_documents
  add column if not exists uploaded_by text;
alter table if exists provider_documents
  add column if not exists created_at timestamptz;
alter table if exists provider_documents
  add column if not exists updated_at timestamptz;

update provider_documents
set original_name = coalesce(nullif(original_name, ''), file_name)
where original_name is null or original_name = '';

update provider_documents
set file_path = coalesce(nullif(file_path, ''), file_name)
where file_path is null or file_path = '';

update provider_documents
set uploaded_at = coalesce(uploaded_at, created_at, now())
where uploaded_at is null;

update provider_documents
set created_at = coalesce(created_at, uploaded_at, now())
where created_at is null;

update provider_documents
set updated_at = coalesce(updated_at, created_at, uploaded_at, now())
where updated_at is null;

update provider_documents
set document_type = 'Other'
where document_type is null or btrim(document_type) = '';

alter table if exists provider_documents
  alter column document_type set default 'Other';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'provider_documents_document_type_check'
  ) then
    alter table provider_documents
      add constraint provider_documents_document_type_check
      check (document_type in ('CV', 'Certificate', 'Company Profile', 'Contract', 'Portfolio', 'Reference', 'Other'))
      not valid;
  end if;
end $$;

alter table if exists provider_documents
  validate constraint provider_documents_document_type_check;

create index if not exists provider_documents_provider_id_uploaded_at_idx
  on provider_documents(provider_id, uploaded_at desc);
